# Generated by Django 5.1.1 on 2024-10-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_cart_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
    ]
