# Generated by Django 5.1.1 on 2024-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_rename_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=124)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
