# Generated by Django 5.1.1 on 2024-09-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom user', 'verbose_name_plural': 'Custom users'},
        ),
    ]
